
[window]
opacity = 0.6
dynamic_padding = true
decorations = "full"

[window.padding]
x = 20
y = 9

[env]
TERM = "xterm-256color"

[font]
size = 7.5

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[general]
import = [
  "~/.config/alacritty/themes/themes/coolnight.toml"
]

# [colors.primary]
# background = "0x000000"
# foreground = "0xffffff"
