[window]
opacity = 0.85
dynamic_padding = true
decorations = "full"

[window.padding]
x = 20
y = 10

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

# [colors.primary]
# background = "0x000000"
# foreground = "0xffffff"
